_BASE_: "Base-BlendMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [True, True, True, True]
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/blendmask/R_50_1x"
