_BASE_: "Base-CRMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FCOS:
    USE_DEFORMABLE: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  STEPS: (420000, 500000)
  MAX_ITER: 540000
OUTPUT_DIR: "output/crmask_MS_R_101_3x"
