_BASE_: "Base-CRMask.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  FCOS:
    USE_DEFORMABLE: False
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/crmask_MS_R_101_1x"
